import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        surface: "#f9f9f6",
        "surface-dim": "#dadad7",
        "surface-bright": "#f9f9f6",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f4f4f1",
        "surface-container": "#eeeeeb",
        "surface-container-high": "#e8e8e5",
        "surface-container-highest": "#e2e3e0",
        "on-surface": "#1a1c1b",
        "on-surface-variant": "#434842",
        "inverse-surface": "#2f312f",
        "inverse-on-surface": "#f1f1ee",
        outline: "#747871",
        "outline-variant": "#c4c8c0",
        "surface-tint": "#526351",
        primary: "#0f1e10",
        "on-primary": "#ffffff",
        "primary-container": "#243324",
        "on-primary-container": "#8a9c88",
        "inverse-primary": "#bacbb6",
        secondary: "#a13f25",
        "on-secondary": "#ffffff",
        "secondary-container": "#fd8364",
        "on-secondary-container": "#721c06",
        tertiary: "#111e10",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#253324",
        "on-tertiary-container": "#8c9c88",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "primary-fixed": "#d5e8d1",
        "primary-fixed-dim": "#bacbb6",
        "on-primary-fixed": "#101f11",
        "on-primary-fixed-variant": "#3b4b3a",
        "secondary-fixed": "#ffdad2",
        "secondary-fixed-dim": "#ffb4a2",
        "on-secondary-fixed": "#3c0700",
        "on-secondary-fixed-variant": "#812810",
        "tertiary-fixed": "#d7e7d1",
        "tertiary-fixed-dim": "#bbcbb6",
        "on-tertiary-fixed": "#111f11",
        "on-tertiary-fixed-variant": "#3c4b3a",
        background: "#f9f9f6",
        "on-background": "#1a1c1b",
        "surface-variant": "#e2e3e0",
        "line-green": "#06C755",
        "line-dark": "#05B04B",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        sm: "0.125rem",
        md: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        full: "9999px",
      },
      spacing: {
        "space-2xs": "0.25rem",
        "space-xs": "0.5rem",
        "space-sm": "0.75rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2rem",
        "space-2xl": "3rem",
        "space-3xl": "4.5rem",
        "space-4xl": "6rem",
        "gutter-mobile": "1rem",
        "gutter-tablet": "1.5rem",
        "gutter-desktop": "2.5rem",
        "container-max": "1360px",
      },
      fontFamily: {
        serif: ["'Noto Serif Thai'", "'Noto Serif'", "serif"],
        sans: ["'Prompt'", "'Plus Jakarta Sans'", "sans-serif"],
      },
    },
  },
  plugins: [],
};

export default config;
