import { Product } from './types';

export const PRODUCTS: Product[] = [
  {
    id: 'pittaya-standard-basket',
    name: 'กระเช้าผลไม้คัดสด Pittaya Standard Basket',
    category: 'basket',
    subtitle: 'ผลไม้ไทยคัดพิเศษตามฤดูกาลและผลไม้นำเข้ายอดนิยม คุ้มค่า สวยงามลงตัว',
    description: 'กระเช้าผลไม้สดคัดสรรคุณภาพคุ้มค่า จัดลงกระเช้าไม้ไผ่ธรรมชาติ คัดผลไม้สดใหม่อย่าง ส้มแมนดาริน, สาลี่หิมะ, แอปเปิ้ลพรีเมียม, กีวี และผลไม้ไทยคัดพิเศษตามฤดูกาล พร้อมบริการผูกริบบิ้นฟรี เหมาะสำหรับเยี่ยมญาติ ของขวัญแสดงความยินดี และโอกาสทั่วไป',
    lotNumber: 'PT-010',
    basePrice: 1000,
    image: '/placeholder-white.svg',
    highlights: ['ผลไม้สดใหม่ทุกเช้า', 'ราคาคุ้มค่าเข้าถึงง่าย', 'ผูกริบบิ้นฟรี'],
    isLimitedRelease: false,
    stockRemaining: 15,
    availableSizes: [
      { size: '12"', label: 'ขนาด 12" (฿1,000)', fruitCount: 'เหมาะสำหรับ 2-3 ท่าน', priceModifier: 0 },
      { size: '14"', label: 'ขนาด 14" (฿1,500)', fruitCount: 'เหมาะสำหรับ 4-6 ท่าน', priceModifier: 500 },
      { size: '16"', label: 'ขนาด 16" (฿2,500)', fruitCount: 'เหมาะสำหรับ 8 ท่านขึ้นไป', priceModifier: 1500 },
    ],
  },
  {
    id: 'pittaya-grand-premium-basket',
    name: 'กระเช้าผลไม้พรีเมียมนำเข้า Pittaya Grand Premium',
    category: 'basket',
    subtitle: 'รวมผลไม้นำเข้าเกรดลักชัวรี องุ่นไชน์มัสกัต เมล่อน สาลี่หิมะ หรูหราสมเกียรติ',
    description: 'กระเช้าผลไม้พรีเมียมระดับท็อปของร้านผลไม้เจ๊อึ่ง คัดสรรผลไม้นำเข้าชั้นเลิศ เช่น องุ่นไชน์มัสกัตลูกโต, เมล่อนญี่ปุ่นหวานฉ่ำ, สาลี่หิมะเกาหลี, พลับสด และผลไม้นำเข้าคัดพิเศษ จัดลงกระเช้าไม้ไผ่ประณีต ผูกริบบิ้นฟรี หรูหราสมเกียรติสำหรับมอบให้ผู้ใหญ่คนสำคัญและลูกค้า VIP',
    lotNumber: 'PT-020',
    basePrice: 1500,
    image: '/placeholder-white.svg',
    highlights: ['องุ่นไชน์มัสกัต & เมล่อน', 'ผลไม้นำเข้าคัดพิเศษ', 'ผูกริบบิ้นฟรี'],
    isLimitedRelease: true,
    stockRemaining: 10,
    availableSizes: [
      { size: '12"', label: 'ขนาด 12" (฿1,500)', fruitCount: 'เหมาะสำหรับ 2-3 ท่าน', priceModifier: 0 },
      { size: '14"', label: 'ขนาด 14" (฿2,500)', fruitCount: 'เหมาะสำหรับ 4-6 ท่าน', priceModifier: 1000 },
      { size: '16"', label: 'ขนาด 16" (฿4,000)', fruitCount: 'เหมาะสำหรับ 8 ท่านขึ้นไป', priceModifier: 2500 },
    ],
  },
  {
    id: 'signature-gift-box',
    name: 'กล่องของขวัญผลไม้สด Signature Gift Box',
    category: 'gift-box',
    subtitle: 'ทางเลือกของขวัญราคาย่อมเยา สวยหรู กะทัดรัด (More affordable alternative)',
    description: 'ทางเลือกของขวัญผลไม้สดที่ราคาย่อมเยากว่ากระเช้าใหญ่ กะทัดรัด สวยงาม บรรจุกีวีสีทอง เชอร์รี่แดงสด ส้มฮันนี่ และแอปเปิ้ลพรีเมียม ในกล่องของขวัญผูกริบบิ้นฟรี สวยงามพร้อมมอบ',
    lotNumber: 'PT-030',
    basePrice: 690,
    image: '/placeholder-white.svg',
    highlights: ['ราคาย่อมเยากว่ากระเช้า', 'สวยหรู กะทัดรัด', 'ผูกริบบิ้นฟรี'],
    isLimitedRelease: false,
    stockRemaining: 15,
  },
  {
    id: 'luxe-berry-citrus-box',
    name: 'กล่องของขวัญผลไม้สด Premium Berry & Citrus Box',
    category: 'gift-box',
    subtitle: 'เซ็ตของขวัญผลไม้นำเข้า สตรอว์เบอร์รี่สด บลูเบอร์รี่ และส้มหวาน',
    description: 'กล่องของขวัญผลไม้รวม สตรอว์เบอร์รี่สดลูกโต บลูเบอร์รี่ และส้มนำเข้าหวานฉ่ำ เหมาะสำหรับมอบในวันเกิด วันครบรอบ เยี่ยมผู้ป่วย และของขวัญแสดงความยินดี',
    lotNumber: 'PT-040',
    basePrice: 890,
    image: '/placeholder-white.svg',
    highlights: ['ทางเลือกของขวัญคุ้มค่า', 'ผลไม้สดพร้อมทาน', 'ผูกริบบิ้นฟรี'],
    isLimitedRelease: true,
    stockRemaining: 8,
  },
  {
    id: 'executive-meeting-box',
    name: 'เซ็ตผลไม้จัดเบรค Executive Fruit Break Box',
    category: 'mini-box',
    subtitle: 'สำหรับงานประชุมผู้บริหาร สัมมนา งานเลี้ยง และกิจกรรมกลุ่ม (ขั้นต่ำ 10 กล่อง)',
    description: 'ผลไม้ปอกสด สะอาด ผ่านการล้างฆ่าเชื้อด้วยโอโซน บรรจุกล่องเดี่ยวพร้อมส้อมไม้รักษ์โลก เหมาะสำหรับงานประชุม สัมมนา งานอีเวนต์ และกิจกรรมบริษัท',
    lotNumber: 'PT-050',
    basePrice: 150,
    image: '/placeholder-white.svg',
    highlights: ['ขั้นต่ำ 10 กล่อง', 'พร้อมส้อมไม้ทานสะดวก', 'จัดส่งรถยนต์เดลิเวอรี่'],
    isLimitedRelease: false,
    bulkDiscounts: [
      { minQuantity: 10, pricePerUnit: 150 },
      { minQuantity: 20, pricePerUnit: 135 },
      { minQuantity: 50, pricePerUnit: 120 },
    ],
  },
  {
    id: 'wellness-break-box',
    name: 'เซ็ตผลไม้สดคละชนิด Wellness Activity Box',
    category: 'mini-box',
    subtitle: 'สำหรับกิจกรรมเวิร์กช็อป ปาร์ตี้กลุ่ม และอาหารว่างช่วงพักเบรค',
    description: 'ผลไม้รวมหั่นชิ้นสดใหม่ กีวี แก้วมังกร องุ่นไร้เมล็ด บรรจุกล่องขนาดกะทัดรัด สะดวกต่อการแจกในกิจกรรมนอกสถานที่และงานอบรม',
    lotNumber: 'PT-060',
    basePrice: 120,
    image: '/placeholder-white.svg',
    highlights: ['ขั้นต่ำ 10 กล่อง', 'พร้อมส้อมไม้ทานสะดวก', 'ผลไม้สดพร้อมทาน'],
    isLimitedRelease: false,
    bulkDiscounts: [
      { minQuantity: 10, pricePerUnit: 120 },
      { minQuantity: 20, pricePerUnit: 110 },
      { minQuantity: 50, pricePerUnit: 100 },
    ],
  },
];

export const LINE_OA_CONFIG = {
  storeName: 'Pittaya Fruits (ร้านผลไม้เจ๊อึ่ง)',
  businessName: 'Pittaya Fruits',
  lineId: 'LINE OA',
  lineUrl: 'https://lin.ee/5zUrw47',
  qrCodeImage: '/line-qr.png',
  phone: '082-659-8893',
  storeHours: '06:00 - 15:30 (หน้าร้าน จ.-ส.) / รับออเดอร์ทาง LINE ทุกวัน',
  address: 'ซอยนวมินทร์ 8 แขวงคลองจั่น เขตบางกะปิ กรุงเทพฯ 10240',
  googleMapsUrl: 'https://maps.app.goo.gl/17sYdGdrdtuvJYPG9',
  coordinates: {
    lat: 13.7748255,
    lng: 100.6456941,
  },
  experienceYears: '20+',
  basketsDelivered: '1,000+',
  tagline: 'ประสบการณ์กว่า 20 ปี คัดผลไม้สดด้วยความใส่ใจ ในราคาที่เข้าถึงได้สำหรับทุกคน',
};
