import { Product } from './types';

export const PRODUCTS: Product[] = [
  {
    id: 'grand-reserve-basket',
    name: 'กระเช้าผลไม้พรีเมียม Atelier Grand Reserve',
    category: 'basket',
    subtitle: 'กระเช้าผลไม้งานสานไม้ไผ่ คัดเกรดประมูลพิเศษ สไตล์ Mizumono',
    description: 'กระเช้าผลไม้ซิกเนเจอร์อันดับ 1 ของร้าน คัดสรรผลไม้สดใหม่ทุกเช้า นำเข้าและผลไม้ไทยพรีเมียม (องุ่นไชน์มัสกัต, สาลี่หิมะเกาหลี, มะเดื่อฝรั่ง, ส้มฮันนี่แมนดาริน) จัดลงกระเช้าไม้ไผ่สาน ผูกริบบิ้นผ้าไหมและการ์ดเขียนอวยพรฟรี',
    brixIndex: 'Peak 18° Brix',
    lotNumber: 'Lot #042',
    basePrice: 1890,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCSUb-V5i1CsXqJmKvCQdb0A0t3PqruJP0c9X5Rxko74-_HuQ9tQMuSEi80vRisGCAdVCcXqxLkhT6JejveuLUTBZt-iUsV0bxfT8iH16C5Nq0ZY_TaHRTe9x1TnXP_Ygq5d4pPvEJbzOVoJigEt0BeO0epoWTuswVt6-FPACP_7OfrMLnHt-0HcNFS0RLnnVRQE2JUuHACNFd0-oqSSzrEqoksCNiY55woviBG6GBfLoCXjvxNDYOo',
    highlights: ['กระเช้าไม้ไผ่สานมือ', 'รถส่งควบคุมอุณหภูมิ', 'รับประกันความหวาน 100%'],
    isLimitedRelease: true,
    stockRemaining: 8,
    availableSizes: [
      { size: '12"', label: '12" Petite (4-6 ชนิด)', fruitCount: 'เหมาะสำหรับ 2-3 ท่าน', priceModifier: 0 },
      { size: '14"', label: '14" Signature (7-9 ชนิด)', fruitCount: 'เหมาะสำหรับ 4-6 ท่าน', priceModifier: 600 },
      { size: '16"', label: '16" Grand Atelier (10-14 ชนิด)', fruitCount: 'เหมาะสำหรับ 8 ท่านขึ้นไป', priceModifier: 1400 },
    ],
    availableTiers: [
      { tier: 'Standard', label: 'Standard Harvest', description: 'ผลไม้คัดเกรดพรีเมียมตามฤดูกาล สด หวานฉ่ำ', priceModifier: 0 },
      { tier: 'Premium', label: 'Premium Reserve (+฿800)', description: 'อัปเกรดผลไม้นำเข้าพิเศษ เช่น องุ่นไชน์มัสกัตคัดช่อใหญ่ & เมล่อนญี่ปุ่น', priceModifier: 800 },
    ],
  },
  {
    id: 'heritage-orchard-basket',
    name: 'กระเช้าผลไม้ Heritage Orchard Harvest',
    category: 'basket',
    subtitle: 'คัดสรรผลไม้เนื้อหวานฉ่ำ เมล่อนญี่ปุ่น ลูกพีช และเชอร์รี่',
    description: 'กระเช้าผลไม้แห่งความอุดมสมบูรณ์ ผสมผสานผลไม้เมล่อนญี่ปุ่นหวานฉ่ำ ลูกพีชขาว และเชอร์รี่สีทับทิม บรรจุในกระเช้าไม้งามสง่า เหมาะสำหรับมอบเป็นของขวัญผู้ใหญ่และวันสำคัญ',
    brixIndex: 'Peak 16.5° Brix',
    lotNumber: 'Lot #045',
    basePrice: 2190,
    image: 'https://images.unsplash.com/photo-1610832958506-aa56368176cf?auto=format&fit=crop&q=80&w=800',
    highlights: ['ผลไม้นำเข้าคัดพิเศษ', 'สไตล์ญี่ปุ่น Mizumono', 'ผูกริบบิ้น & การ์ดอวยพรฟรี'],
    isLimitedRelease: false,
    availableSizes: [
      { size: '12"', label: '12" Petite (4-6 ชนิด)', fruitCount: 'เหมาะสำหรับ 2-3 ท่าน', priceModifier: 0 },
      { size: '14"', label: '14" Signature (7-9 ชนิด)', fruitCount: 'เหมาะสำหรับ 4-6 ท่าน', priceModifier: 600 },
      { size: '16"', label: '16" Grand Atelier (10-14 ชนิด)', fruitCount: 'เหมาะสำหรับ 8 ท่านขึ้นไป', priceModifier: 1400 },
    ],
    availableTiers: [
      { tier: 'Standard', label: 'Standard Harvest', description: 'ผลไม้สดตามฤดูกาลคัดสรรพิเศษ', priceModifier: 0 },
      { tier: 'Premium', label: 'Premium Reserve (+฿800)', description: 'อัปเกรดผลไม้หายากเกรดพรีเมียมพิเศษ', priceModifier: 800 },
    ],
  },
  {
    id: 'signature-gift-box',
    name: 'กล่องของขวัญผลไม้สด Signature Gift Box',
    category: 'gift-box',
    subtitle: 'เซ็ตของขวัญผลไม้พรีเมียม ราคาจับต้องได้ สวยหรูสไตล์มินิมอล',
    description: 'กล่องของขวัญผลไม้สดคัดพิเศษ บรรจุกีวีสีทอง เชอร์รี่แดงสด เบอร์รี่รวม และส้มฮันนี่หวานฉ่ำ ในกล่องผ้าลินินคราฟต์สุดหรู ผูกริบบิ้นผ้าไหมซิกเนเจอร์',
    brixIndex: 'Peak 15.8° Brix',
    lotNumber: 'Lot #048',
    basePrice: 890,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuC-pgkBMgtGVyHD9V_MI2q5lm4X4MIsS-ZBXCG1Qyl1-A0IzX-_EVSdoDPoCXZOGASfJdrp_TFx0I4E9EKipWoQQBRYnjVmBfRb_4R1vXsycynAtGG9eMuX88L-uLOUaAvCdU6jIZLP3WQdoxRCQNR8bBdfnqbfazL7c1TRpMONmHXodQ-E-VzzlQTwxaEx3G8w24NSAnqx9JPkoEiQhlho8mz6YtHCZJFwGqSk3nixwLpVr4L9QD9Q',
    highlights: ['กล่องของขวัญคราฟต์พรีเมียม', 'ล้างสะอาดพร้อมทาน', 'ของขวัญราคาคุ้มค่า'],
    isLimitedRelease: false,
    stockRemaining: 15,
  },
  {
    id: 'luxe-berry-citrus-box',
    name: 'กล่องของขวัญ Luxe Berry & Honey Citrus',
    category: 'gift-box',
    subtitle: 'เบอร์รี่สดลูกโต ผสมผสานส้มหวานไร้เมล็ดนำเข้า',
    description: 'กล่องของขวัญผลไม้รวม สตรอว์เบอร์รี่สดลูกโต บลูเบอร์รี่ และส้มเดโคปองหวานฉ่ำ เหมาะสำหรับวันเกิด วันครบรอบ และของขวัญแสดงความยินดี',
    brixIndex: 'Peak 17.2° Brix',
    lotNumber: 'Lot #051',
    basePrice: 1290,
    image: 'https://images.unsplash.com/photo-1519996529931-28324d5a630e?auto=format&fit=crop&q=80&w=800',
    highlights: ['สตรอว์เบอร์รี่เกรดพรีเมียม', 'รสหวานธรรมชาติ 100%', 'ผูกริบบิ้นผ้าไหมฟรี'],
    isLimitedRelease: true,
    stockRemaining: 6,
  },
  {
    id: 'mini-meeting-break-box',
    name: 'เซ็ตผลไม้จัดเบรค Mini Event & Break Box',
    category: 'mini-box',
    subtitle: 'ผลไม้ปอกสดพร้อมทาน สำหรับงานประชุม สัมมนา และกิจกรรม (ขั้นต่ำ 10 กล่อง)',
    description: 'เซ็ตผลไม้ปอกสด สะอาด ปลอดภัย ผ่านการล้างด้วยโอโซน บรรจุกล่องเดี่ยวพร้อมส้อมไม้รักษ์โลก เหมาะสำหรับงานประชุมสัมมนา เวิร์กช็อป และกิจกรรมบริษัท',
    brixIndex: 'Peak 15° Brix',
    lotNumber: 'Lot #055',
    basePrice: 150,
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&q=80&w=800',
    highlights: ['ขั้นต่ำ 10 กล่อง', 'ล้างโอโซน สะอาดพร้อมทาน', 'แถมส้อมไม้รักษ์โลกฟรี'],
    isLimitedRelease: false,
    bulkDiscounts: [
      { minQuantity: 10, pricePerUnit: 150 },
      { minQuantity: 20, pricePerUnit: 135 },
      { minQuantity: 50, pricePerUnit: 120 },
    ],
  },
  {
    id: 'mini-executive-wellness-pack',
    name: 'เซ็ตผลไม้สุขภาพ Event Wellness Pack',
    category: 'mini-box',
    subtitle: 'ผลไม้ซูเปอร์ฟู้ด อุดมด้วยสารต้านอนุมูลอิสระ (ขั้นต่ำ 10 กล่อง)',
    description: 'ถ้วยผลไม้สุขภาพรวม แก้วมังกร ทับทิม บลูเบอร์รี่สด และกีวีออร์แกนิก สำหรับงานประชุมระดับผู้บริหารและกิจกรรมเพื่อสุขภาพ',
    brixIndex: 'Peak 14.8° Brix',
    lotNumber: 'Lot #058',
    basePrice: 180,
    image: 'https://images.unsplash.com/photo-1490474418585-ba9bad8fd0ea?auto=format&fit=crop&q=80&w=800',
    highlights: ['ขั้นต่ำ 10 กล่อง', 'ซูเปอร์ฟู้ดเพื่อสุขภาพ', 'จัดส่งด้วยความเย็น'],
    isLimitedRelease: false,
    bulkDiscounts: [
      { minQuantity: 10, pricePerUnit: 180 },
      { minQuantity: 20, pricePerUnit: 160 },
      { minQuantity: 50, pricePerUnit: 140 },
    ],
  },
];

export const LINE_OA_CONFIG = {
  storeName: 'Pittaya Fruits (ร้านผลไม้เจ๊อึ่ง)',
  lineId: 'LINE OA',
  lineUrl: 'https://lin.ee/5zUrw47',
  qrCodeImage: '/line-qr.png',
  phone: '081-234-5678',
  storeHours: '08:00 - 20:00 (เปิดบริการทุกวัน)',
  address: 'Pittaya Fruits (ร้านผลไม้เจ๊อึ่ง), คลองจั่น บางกะปิ กรุงเทพฯ 10240',
  googleMapsUrl: 'https://maps.app.goo.gl/17sYdGdrdtuvJYPG9',
  coordinates: {
    lat: 13.7748255,
    lng: 100.6456941,
  },
};
