import { Product } from './types';

export const PRODUCTS: Product[] = [
  {
    id: 'grand-reserve-basket',
    name: 'กระเช้าผลไม้พรีเมียม Pittaya Grand Basket',
    category: 'basket',
    subtitle: 'กระเช้าผลไม้สดคัดพิเศษ ประสบการณ์กว่า 20 ปี จัดลงกระเช้างานสานสวยงาม',
    description: 'กระเช้าผลไม้ซิกเนเจอร์อันดับ 1 ของร้านผลไม้เจ๊อึ่ง คัดสรรผลไม้สดใหม่ทุกเช้า ทั้งผลไม้นำเข้าและผลไม้ไทยคัดพิเศษ (องุ่นไชน์มัสกัต, สาลี่หิมะ, มะเดื่อฝรั่ง, ส้มแมนดาริน, เมล่อน) จัดลงกระเช้าไม้ไผ่ ผูกริบบิ้นผ้าไหมและการ์ดเขียนอวยพรฟรี',
    lotNumber: 'Lot #042',
    basePrice: 1000,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCSUb-V5i1CsXqJmKvCQdb0A0t3PqruJP0c9X5Rxko74-_HuQ9tQMuSEi80vRisGCAdVCcXqxLkhT6JejveuLUTBZt-iUsV0bxfT8iH16C5Nq0ZY_TaHRTe9x1TnXP_Ygq5d4pPvEJbzOVoJigEt0BeO0epoWTuswVt6-FPACP_7OfrMLnHt-0HcNFS0RLnnVRQE2JUuHACNFd0-oqSSzrEqoksCNiY55woviBG6GBfLoCXjvxNDYOo',
    highlights: ['ประสบการณ์ 20+ ปี', 'ส่งด้วยรถยนต์แอร์ถึงที่', 'ผูกริบบิ้น & การ์ดอวยพรฟรี'],
    isLimitedRelease: true,
    stockRemaining: 10,
    availableSizes: [
      { size: '12"', label: 'ขนาด 12" (Standard ฿1,000 / Premium ฿1,500)', fruitCount: 'เหมาะสำหรับ 2-3 ท่าน', priceModifier: 0 },
      { size: '14"', label: 'ขนาด 14" (Standard ฿2,000 / Premium ฿2,500)', fruitCount: 'เหมาะสำหรับ 4-6 ท่าน', priceModifier: 1000 },
      { size: '16"', label: 'ขนาด 16" (Standard ฿3,000 / Premium ฿3,500)', fruitCount: 'เหมาะสำหรับ 8 ท่านขึ้นไป', priceModifier: 2000 },
    ],
    availableTiers: [
      { tier: 'Standard', label: 'Standard Tier (฿1,000 - ฿3,000)', description: 'ผลไม้คัดเกรดพรีเมียมตามฤดูกาล สด หวานฉ่ำ คัดสรรอย่างดี', priceModifier: 0 },
      { tier: 'Premium', label: 'Premium Tier (+฿500)', description: 'อัปเกรดผลไม้นำเข้าพิเศษ ช่อใหญ่ เช่น องุ่นไชน์มัสกัต & เมล่อนญี่ปุ่นเกรดพรีเมียม', priceModifier: 500 },
    ],
  },
  {
    id: 'signature-gift-box',
    name: 'กล่องของขวัญผลไม้สด Signature Gift Box',
    category: 'gift-box',
    subtitle: 'ทางเลือกของขวัญราคาย่อมเยา สวยหรู กะทัดรัด (More affordable alternative)',
    description: 'ทางเลือกของขวัญผลไม้สดที่ราคาย่อมเยากว่ากระเช้าใหญ่ กะทัดรัด สวยงาม บรรจุกีวีสีทอง เชอร์รี่แดงสด ส้มฮันนี่ และแอปเปิ้ลพรีเมียม ในกล่องของขวัญผูกริบบิ้นผ้าไหมและการ์ดอวยพรฟรี',
    lotNumber: 'Lot #048',
    basePrice: 690,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuC-pgkBMgtGVyHD9V_MI2q5lm4X4MIsS-ZBXCG1Qyl1-A0IzX-_EVSdoDPoCXZOGASfJdrp_TFx0I4E9EKipWoQQBRYnjVmBfRb_4R1vXsycynAtGG9eMuX88L-uLOUaAvCdU6jIZLP3WQdoxRCQNR8bBdfnqbfazL7c1TRpMONmHXodQ-E-VzzlQTwxaEx3G8w24NSAnqx9JPkoEiQhlho8mz6YtHCZJFwGqSk3nixwLpVr4L9QD9Q',
    highlights: ['ราคาย่อมเยากว่ากระเช้า', 'สวยหรู กะทัดรัด', 'ผูกริบบิ้น & การ์ดอวยพรฟรี'],
    isLimitedRelease: false,
    stockRemaining: 15,
  },
  {
    id: 'luxe-berry-citrus-box',
    name: 'กล่องของขวัญผลไม้สด Premium Berry & Citrus Box',
    category: 'gift-box',
    subtitle: 'เซ็ตของขวัญผลไม้นำเข้า สตรอว์เบอร์รี่สด บลูเบอร์รี่ และส้มหวาน',
    description: 'กล่องของขวัญผลไม้รวม สตรอว์เบอร์รี่สดลูกโต บลูเบอร์รี่ และส้มนำเข้าหวานฉ่ำ เหมาะสำหรับมอบในวันเกิด วันครบรอบ เยี่ยมผู้ป่วย และของขวัญแสดงความยินดี',
    lotNumber: 'Lot #051',
    basePrice: 890,
    image: 'https://images.unsplash.com/photo-1519996529931-28324d5a630e?auto=format&fit=crop&q=80&w=800',
    highlights: ['ทางเลือกของขวัญคุ้มค่า', 'ผลไม้สดพร้อมทาน', 'ผูกริบบิ้นผ้าไหมฟรี'],
    isLimitedRelease: true,
    stockRemaining: 8,
  },
  {
    id: 'executive-meeting-box',
    name: 'เซ็ตผลไม้จัดเบรค Executive Fruit Break Box',
    category: 'mini-box',
    subtitle: 'สำหรับงานประชุมผู้บริหาร สัมมนา งานเลี้ยง และกิจกรรมกลุ่ม (ขั้นต่ำ 10 กล่อง)',
    description: 'ผลไม้ปอกสด สะอาด ผ่านการล้างฆ่าเชื้อด้วยโอโซน บรรจุกล่องเดี่ยวพร้อมส้อมไม้รักษ์โลก เหมาะสำหรับงานประชุม สัมมนา งานอีเวนต์ และกิจกรรมบริษัท',
    lotNumber: 'Lot #055',
    basePrice: 150,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAMsZ4gL7r3v5BwX81J72m8L4KzG_u6sYqTz2c_N1qV_L6WJ_z7b1bJ0D2vQ3j-xG5t8m6c1R3k8n9A4Y_w2e1d0f5g7h8i9j',
    highlights: ['ขั้นต่ำ 10 กล่อง', 'งานประชุม & สัมมนา', 'จัดส่งรถยนต์เดลิเวอรี่'],
    isLimitedRelease: false,
    bulkDiscounts: [
      { minQuantity: 10, pricePerUnit: 150 },
      { minQuantity: 20, pricePerUnit: 135 },
      { minQuantity: 50, pricePerUnit: 120 },
    ],
  },
  {
    id: 'wellness-break-box',
    name: 'เซ็ตผลไม้สดคละชนิด Wellness Activity Box',
    category: 'mini-box',
    subtitle: 'สำหรับกิจกรรมเวิร์กช็อป ปาร์ตี้กลุ่ม และอาหารว่างช่วงพักเบรค',
    description: 'ผลไม้รวมหั่นชิ้นสดใหม่ กีวี แก้วมังกร องุ่นไร้เมล็ด บรรจุกล่องขนาดกะทัดรัด สะดวกต่อการแจกในกิจกรรมนอกสถานที่และงานอบรม',
    lotNumber: 'Lot #058',
    basePrice: 120,
    image: 'https://images.unsplash.com/photo-1490474418585-ba9bad8fd0ea?auto=format&fit=crop&q=80&w=800',
    highlights: ['ขั้นต่ำ 10 กล่อง', 'กิจกรรมกลุ่ม & เวิร์กช็อป', 'ผลไม้สดพร้อมทาน'],
    isLimitedRelease: false,
    bulkDiscounts: [
      { minQuantity: 10, pricePerUnit: 120 },
      { minQuantity: 20, pricePerUnit: 110 },
      { minQuantity: 50, pricePerUnit: 100 },
    ],
  },
];

export const LINE_OA_CONFIG = {
  storeName: 'Pittaya Fruits (ร้านผลไม้เจ๊อึ่ง)',
  businessName: 'Pittaya Fruits',
  lineId: 'LINE OA',
  lineUrl: 'https://lin.ee/5zUrw47',
  qrCodeImage: '/line-qr.png',
  phone: '082-659-8893',
  storeHours: '06:00 - 15:30 (หน้าร้าน จ.-ส.) / รับออเดอร์ทาง LINE ทุกวัน',
  address: 'ซอยนวมินทร์ 8 แขวงคลองจั่น เขตบางกะปิ กรุงเทพฯ 10240',
  googleMapsUrl: 'https://maps.app.goo.gl/17sYdGdrdtuvJYPG9',
  coordinates: {
    lat: 13.7748255,
    lng: 100.6456941,
  },
  experienceYears: '20+',
  basketsDelivered: '1,000+',
  tagline: 'ประสบการณ์กว่า 20 ปี คัดผลไม้สดด้วยความใส่ใจ ในราคาที่เข้าถึงได้สำหรับทุกคน',
};
